apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appointment-service.fullname" . }}
  labels:
    {{- include "appointment-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "appointment-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "appointment-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appointment-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext.pod | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          securityContext:
            {{- toYaml .Values.securityContext.container | nindent 12 }}
          env:
            - name: REDIS_HOST
              value: {{ include "appointment-service.redisName" . | quote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: APP_VERSION
              value: {{ .Values.config.appVersion | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "appointment-service.fullname" . }}
                  key: redis-password
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
