# Application of Applications for GitOps bootstrap.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointment-service-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/python_devsecops_pipeline_quickstart.git
    targetRevision: main
    path: helm/appointment-service
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: appointment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
